### ISSUE TITLE
[FEA] Add support for RMM logging to rapids-pytest-benchmark

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/benchmark#27]
The new API is here:
https://github.com/rapidsai/rmm/pull/363

- The `rapids-pytest-benchmark` code can effectively replace the code in `gpu_metric_poller.py` with a similar module responsible for reading the log file.
- Since RMM logging adds significant overhead, the benchmark time measurements **cannot** be run when logging is enabled. This is the same case as GPU polling, so the approach already used in `rapids-pytest-benchmark` should not change (ie. separate runs done internally).
- The peak memory usage is what we want to see, since this shows what the resource requirements of our algos are, and we obviously want them to be as low as possible to allow customers to run large datasets.
- _(need to confirm this detail)_ The log contains lines/entries for each alloc and how many bytes were requested, and each free and how many bytes were freed. Algos make several alloc/free calls throughout their lifetime, so the log could get large.
- _(this is based on the assumption above, which needs to be confirmed)_ To compute the peak memory usage, do the following:
  - initialize vars `max` and `total` to 0.
  - for each alloc, add the number of bytes to `total`.  If `total > max`, set `max = total`
  - for each free, subtract the number of bytes from `total`
  - at the end of the benchmark run, return `max` as peak memory usage
  - **bonus:** at the end of the benchmark run, `total` should be `0`.  If not, report `total` as the number of leaked bytes.

**Comment by rlratzel** [comment]
@dillon-cullinan is working on this and is planning on having it done post-MVP timeframe.

**Comment by ajschmidt8** [comment]
adding a link to the relevant `rmm` issue below for reference

https://github.com/rapidsai/rmm/issues/423

**Comment by ajschmidt8** [comment]
Blocked by https://github.com/rapidsai/rmm/issues/721

**Comment by ajschmidt8** [comment]
Unblocked with the merge of https://github.com/rapidsai/rmm/pull/722

**Comment by ajschmidt8** [comment]
#62 is merged which closes this issue.

Packages have been built and uploaded to Anaconda.org:

- https://anaconda.org/rapidsai/rapids-pytest-benchmark
- https://anaconda.org/rapidsai-nightly/rapids-pytest-benchmark
