### ISSUE TITLE
Move asvdb and rapids-pytest-plugin to proper RAPIDS repos, and conda package to rapidsai channel

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/benchmark#37]
- [x] `rapids-pytest-benchmark` repo to rapidsai
- [x] `asvdb` repo to rapidsai
- [x] `rapids-pytest-benchmark` conda package to rapidsai
- [x] `asvdb` conda package to rapidsai

**Comment by dillon-cullinan** [comment]
I think moving them to this repo is already okay. In terms of the conda package, are you currently building it manually or do you have a build script/jenkins job of any sort? I may just create a small Jenkins job to support its release for whenever we need.

**Comment by rlratzel** [comment]
> In terms of the conda package, are you currently building it manually or do you have a build script/jenkins job of any sort?

Thanks @dillon-cullinan .  I currently build them manually whenever I make a change. I also have to manually update the version number which isn't ideal.  There a small build scripts for both that I run.

**Comment by ajschmidt8** [comment]
FYI, currently in progress by me

**Comment by ajschmidt8** [comment]
asvdb repo: https://github.com/rapidsai/asvdb

**Comment by ajschmidt8** [comment]
asvdb conda: https://anaconda.org/rapidsai/asvdb

**Comment by rlratzel** [comment]
@ajschmidt8 can you check off the `rapids-pytest-benchmark` in the description here and close this issue when it gets built & published? I'll take @dillon-cullinan off the assignee list.

**Comment by ajschmidt8** [comment]
`rapids-pytest-benchmark on `rapidsai` conda channel: https://anaconda.org/rapidsai/rapids-pytest-benchmark
