### ISSUE TITLE
[FEA] Run benchmarks on a repo nightly but somehow show affects of updated dependencies

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/benchmark#39]
We need to run benchmarks on a repo nightly but somehow show affects of updated dependencies (even if benchmarked repo doesn't change).

The issue here is a benchmark run will happen every night even if there were no commits to the repo (meaning no code for the repo being benchmarked should theoretically affect benchmark perf vs. the previous run).  However, since other components in the stack probably did change and were rebuilt, those could affect performance.

Since the benchmark runs don't capture info about a dependency change - and even worse, will overwrite the previous run if the repo's commit hash didn't change - we need to somehow capture that the run is unique and is using a different set of dependencies (ie. different builds of other RAPIDS components it depends on)even when the component itself didn't change.

**Comment by dillon-cullinan** [comment]
This should be done.
